name: movies_demo_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cached_network_image: ^3.2.0
  connectivity_plus: ^2.2.1
  cupertino_icons: ^1.0.2
  firebase_core: ^1.13.1
  firebase_messaging: ^11.2.11
  flutter:
    sdk: flutter
  flutter_local_notifications: ^9.4.0
  flutter_spinkit: ^5.1.0
  get: ^4.6.1
  google_fonts: ^2.3.1
  overlay_support: ^1.2.1
  provider: ^6.0.2
  shimmer: ^2.0.0
  staggered_grid_view_flutter: ^0.0.4
  tmdb_api: ^2.1.0

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path_android: "assets/logo.png"
  image_path_ios: "assets/logo.png"
  adpative_icon_background: "#6833FF"
  adpative_icon_foreground: "assets/images/logo.png"
  android: true
  ios: true

flutter:

  uses-material-design: true
  assets:
    - assets/
